# This workflow will run on every pull request to the master branch,

# This is the name of the workflow, every workflow needs a name
name: NODE CONTINOUS INTEGRATION WORKFLOW

# Here we specify on which action in the repository that we want to run this workflow, e.g push, pull_request, commit, pull e.t.c

on:
  pull_request:
    branches: [master]

# we define one or more jobs, every workflow should have a job, we can give each job a name

jobs:
  automate_our_testing:

  # we need to tell it which machine to run the job on
  runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job

  steps:
    - uses: actions/checkout@v2 #This pulls our code to the remote machine
    - uses: actions/setup-node@v2 # This setsup node js on the machine
      with:
        node-version: 12
    - run: npm ci # installs our project dependencies
    #- run: npm run build                # builds the project
    - run: npm test # runs our test command
      env:
        CI: true
